export const Phrases = [
  "Sorry, I couldn't log in",
  "I had connection issues",
  "Can you hear me?",
  "You're on mute",
  "Let's circle back to that later",
  "Someone join the meeting late",
  "Hello, hello?",
  "Can everyone see my screen?",
  "Let's take this offline",
  "Is anyone else having problems?",
  "Can you repeat that, please?",
  "Background noise",
  "Awkward silence",
  "Sorry, I was on mute",
  "Can you see my webcam?",
  "Lost internet connection",
  "(load painful echo / feedback)",
  "Waiting for someone to join",
  "Let's wrap this up",
  "I'll follow up with an email",
  "I'm having trouble with my connection.",
  "Next slide, please.",
  "can everyone go on mute",
  "can you email that to everyone?",
  "Share your screen, please.",
  "Attendance check, please.",
  "Sending link in chat.",
  "Bandwidth issues encountered.",
  "Re-entering the meeting.",
  "Consider switching platforms.",
  "Dialing in for better audio.",
  "Adjusting meeting settings.",
  "Resending meeting invite.",
  "Turning off video to save bandwidth.",
  "Could you repeat that?",
  "Can you increase your volume?",
  "Let's switch to a different server.",
  "Let's try refreshing the page.",
  "The video quality is poor.",
  "Is there a screen sharing option?",
  "I'm experiencing a delay in responses.",
  "I'll check my microphone settings.",
  "Please check your microphone.",
  "The meeting link seems to be broken.",
  "I'll try logging in again.",
  "The video froze for a moment.",
  "We're experiencing latency issues.",
  "I'll send you the document via chat.",
  "Is everyone on the call?",
  "I'll try restarting my device.",
];
