export const Phrases = [
  "Sorry, I couldn't log in",
  "I had connection issues",
  "Can you hear me?",
  "You're on mute",
  "Let's circle back to that later",
  "Someone join the meeting late",
  "Hello, hello?",
  "Can everyone see my screen?",
  "Let's take this offline",
  "Is anyone else having problems?",
  "Can you repeat that, please?",
  "Background noise",
  "Awkward silence",
  "Sorry, I was on mute",
  "Can you see my webcam?",
  "Lost internet connection",
  "(load painful echo / feedback)",
  "Waiting for someone to join",
  "Let's wrap this up",
  "I'll follow up with an email",
  "I'm having trouble with my connection.",
  "Next slide, please.",
  "can everyone go on mute",
  "can you email that to everyone?",
];
